In [1]:
#numpy= numerical python

In [2]:
import numpy as np

In [3]:
a=[1,2,4]
b=np.array(a)
b

array([1, 2, 4])

In [4]:
print(type(b))

<class 'numpy.ndarray'>


In [13]:
a=[1,2,4,'5',4.5]
b=np.array(a,dtype=int)
b

array([1, 2, 4, 5, 4])

In [14]:
a=[1,2,4,'5',4.5]
b=np.array(a*3)
b

array(['1', '2', '4', '5', '4.5', '1', '2', '4', '5', '4.5', '1', '2',
       '4', '5', '4.5'], dtype='<U32')

In [16]:
a=np.ones(3)
a

array([1., 1., 1.])

In [18]:
a=np.ones(3,dtype=int)
a

array([1, 1, 1])

In [17]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [19]:
a=np.zeros(3,dtype=int)
a

array([0, 0, 0])

In [25]:
a=np.ones((2,3),dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [31]:
b=np.full((3,2),1)
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [45]:
a=np.empty(2)
a

array([1.38434096e+085, 3.33859454e-273])

In [49]:
a = np.empty(4, dtype = int)
print(a)

[0 0 0 0]


In [50]:
import numpy as np
l=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(l,dtype=int)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
a=np.array(10)
a=np.zeros(10,dtype=int)
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [62]:
print(*a)

0 0 0 0 1 0 0 0 0 0


In [68]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
b=np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
b=np.arange(2,10,3)
b

array([2, 5, 8])

In [74]:
b=np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [77]:
print(b[1]-b[0])
print(b[2]-b[1])

0.16326530612244916
0.16326530612244872


In [88]:
b=np.linspace(2,10,5,dtype=int)
b

array([ 2,  4,  6,  8, 10])

In [93]:
b=np.identity(3,dtype=int)
b


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [96]:
b=np.eye(3,4,dtype=int)
b

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [99]:
b=np.random.rand(3)
b

array([0.47610683, 0.17671715, 0.18048539])

In [101]:
b=np.random.rand(2,3)
b

array([[0.66995314, 0.98320591, 0.55440102],
       [0.42807855, 0.12015082, 0.04733397]])

In [104]:
b=np.random.randint(1,10)
b

4

In [107]:

np.random.randint(10, size = (4, 4))

array([[3, 5, 2, 7],
       [1, 6, 5, 6],
       [7, 6, 3, 7],
       [0, 7, 2, 2]])

In [108]:
np.random.rand()

0.7082378616246431

In [112]:
arr= np.arange(9,46)
print(*arr)

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45


In [114]:
mat=np.eye(5,6,dtype=int)
print(mat)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]
